# Generated by Django 4.2.7 on 2023-11-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=100)),
                ('streetName', models.CharField(max_length=100)),
                ('houseNumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='userId',
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coldWater', models.IntegerField()),
                ('hotWater', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('profileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='buildingId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='portal.building'),
            preserve_default=False,
        ),
    ]
