# Generated by Django 4.2.7 on 2023-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_building_rename_user_userprofile_userid_counter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='profileId',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='userId',
            new_name='user',
        ),
    ]
