# Generated by Django 4.2.7 on 2023-12-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_profileid_counter_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='buildingId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='portal.building'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flatNumber',
            field=models.IntegerField(),
        ),
    ]
