# Generated by Django 4.2.7 on 2023-12-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.userprofile'),
        ),
    ]
