# Generated by Django 4.2.7 on 2023-12-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_counter_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='profile',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='portal.userprofile'),
            preserve_default=False,
        ),
    ]
